### ISSUE TITLE
Does Not Work With .min Suffix

### ISSUE THREAD

**Issue by ddelella** [kaisermann/main-npm-files#1]
```
gulp.task('deploy-js-lib', function() {
    return gulp.src(mainNPMFiles('**/*.min.js'))
        .pipe(gulp.dest(conf.paths.deploy + "/lib"));
});
```

Should return several .min.js files, at least jQuery, but it returns no files.  The .min.css instead returned a single file instead of multiple.  At a minimum there should be a jquery.min.js and a bootstrap.min.css.

If there is any suggestions I would mirror the code for this after main-bower-files and simply change the base directory to .node_modules for npm.

**Comment by kaisermann** [comment]
Both jQuery's and Bootstrap's `package.json` don't specify the `.min.js` version. 

boostrap's:
```json
...
  "main": "./dist/js/npm",
...
```

jQuery's:
```json
...
  "main": "dist/jquery.js",
...
```
Therefore, the `mainNPMFiles('**/*.min.js')` won't find anything.

If I could make an suggestion, you can create an `overrides` property on your `package.json` like this: 

```json
...
  "overrides": {
    "bootstrap": {
      "main": "./dist/js/bootstrap.min.js"
    },
    "jquery": {
      "main": "./dist/jquery.min.js"
    }
  }
...
```

Note: bootstrap doesn't even specify the '.js' file extension...
